import 'package:firebase_core/firebase_core.dart';

/// Owns Firebase initialisation.
///
/// `firebase_options.dart` is generated by the FlutterFire CLI and is **not**
/// committed (it is environment-specific). Until it exists the app must still
/// run, so [initialize] reports failure instead of throwing and
/// [main.dart] falls back to the in-memory repositories. This keeps
/// `flutter run` and `flutter test` working on a fresh clone.
class FirebaseBootstrap {
  const FirebaseBootstrap._();

  static bool _initialized = false;

  /// Whether Firebase is ready. Always `false` until initialisation succeeds.
  static bool get isReady => _initialized;

  /// Attempts to start Firebase.
  ///
  /// Returns `true` on success. Never throws: a missing configuration file or
  /// a Firebase error simply yields `false` so the caller can fall back.
  static Future<bool> initialize() async {
    if (_initialized) return true;
    try {
      await Firebase.initializeApp(
        // Intentionally omitted: `options: DefaultFirebaseOptions.currentPlatform`
        // is only available once `flutterfire configure` has generated the
        // file. On Android/iOS Firebase falls back to the native
        // google-services.json / GoogleService-Info.plist.
      );
      _initialized = true;
      return true;
    } on Object {
      _initialized = false;
      return false;
    }
  }
}